### ISSUE TITLE
Farntech DDK 2400

### ISSUE THREAD

**Issue by DeeDeeRanged** [ddewar/FS22_UniversalAutoloadModhubAddon#107]
Hi any chance for  the Farntech DDK 2400 from the Premium Expansion to be added?
I like the combo FIAT Turbostar and this trailer as together it's awesome for harvested goods, but only the FIAT is UAL.

Many thanks for this awesome mod, keep up the good work.

cheers

**Comment by Andx667** [comment]
the farmtech DDK 2400 ist supportet by the main UA addon https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.4.0

**Comment by DeeDeeRanged** [comment]
Ah ok I see the version is not updated on modhub yet. Installed that latest version and it working. Hope modhub hurries up with this update of FS_UniversalAutoload.

Thanks for pointing it out to me.
