### ISSUE TITLE
In Strautmann SEK 802 v.1.0.0.1 there is no "Unload" item in F1 and does not work.

### ISSUE THREAD

**Issue by vitalii2011** [ddewar/FS22_UniversalAutoloadModhubAddon#13]
- The problem is described in the title. ) https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=223851
-  Added UA icon to mod icons https://i.imgur.com/TgWt0YH.png https://i.imgur.com/2Sc9qpb.png , can your script do it? If - yes, and you are interested, I can send materials how to add quickly and conveniently.

**Comment by ddewar** [comment]
> - The problem is described in the title. ) https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=223851

This is interesting. I'm not sure why just that one trailer would have issues. Maybe check the keybinds? I can try investing more if that doesn't work. 

> -  Added UA icon to mod icons https://i.imgur.com/TgWt0YH.png https://i.imgur.com/2Sc9qpb.png , can your script do it? If - yes, and you are interested, I can send materials how to add quickly and conveniently.

This is interesting, but probably is something more targeted towards the base mod?

**Comment by vitalii2011** [comment]
- Reconfigured the keys - fixed. Sorry to bother you.
- UA adds to vanilla, and for mods it's better in UAMHA. loki_79 has no time now, and so does Ifko[nator]: "Es soll also ein Store Bild von einem Standard Fahrzeug mit einem anderem getauscht werden? Das ist schon möglich, aber nicht so einfach.. Dafür fehlt mir aktuell leider die Zeit". I don't have enough knowledge. ) 
- If anything - I can do icons. 
- Inspiration and time for it.

**Comment by ddewar** [comment]
> * Reconfigured the keys - fixed. Sorry to bother you.
Never a bother, I know this Giants keybind issue has all of us going crazy.

> * UA adds to vanilla, and for mods it's better in UAMHA. loki_79 has no time now, and so does Ifko[nator]: "Es soll also ein Store Bild von einem Standard Fahrzeug mit einem anderem getauscht werden? Das ist schon möglich, aber nicht so einfach.. Dafür fehlt mir aktuell leider die Zeit". I don't have enough knowledge. )

I'll talk with Loki and see what the long-term plan is for some of this. I am going to have to follow his lead to keep it as consistent as possible :) If you think you have something that might work, feel free to send it over or open a PR. Happy to take a look and see how this could work!

> * If anything - I can do icons.
> * Inspiration and time for it.

**Comment by ddewar** [comment]
I'm going to close this issue. Working with Loki we found another way to detail what configurations have UAL set up. Check out his releases for more details. Thanks for the awesome idea and bug report.
