### ISSUE TITLE
Support for Orkel TX 130

### ISSUE THREAD

**Issue by ph-hoffmann** [ddewar/FS22_UniversalAutoloadModhubAddon#14]
Could you add support for the following mod?
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=226465&title=fs2022

It has working side doors but sometimes you just want to hit that button and be done ;)

**Comment by ddewar** [comment]
I'm working on the next update currently. I will do my best to include this one!

**Comment by ddewar** [comment]
Just a status update on this:

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/commit/a5e85564ef444b02f9d5a1e5490874283ba1490d

Hopefully will put out a release in the next day or two.

**Comment by ddewar** [comment]
Check out https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v0.0.6-beta
