### ISSUE TITLE
Support for adurante pack request 

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#16]
hi 

any chance that you can add support for the Adurante Pack https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=232329&title=fs2022

Also i note that this says it was updated 5 hours ago but the release hasnt changed am i supposed to wait for a new release and ignore the last updated info i see

**Comment by ddewar** [comment]
I probably uploaded the wrong version. 🙄 I'll work on fixing that soon. I have been working on the Adurante pack for the next update. I get that in as soon as possible. Should be a few days.

**Comment by ddewar** [comment]
Check out release https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v0.0.6-beta

Let me know if that solves this.
