### ISSUE TITLE
Support for Lizard Trailer Pack

### ISSUE THREAD

**Issue by DrewCZ** [ddewar/FS22_UniversalAutoloadModhubAddon#18]
Here is the tuned XML part: 
```
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD83K.xml" selectedConfigs="1,5,7">
            <loadingArea offset="0 1.65 0" width="2.35" height="3.3" length="6.2"/>
        </vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD83K.xml" selectedConfigs="8">
            <loadingArea offset="0 1.65 0" width="2.6" height="3.3" length="6.2"/>
        </vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD616K.xml" selectedConfigs="1,5,7">
            <loadingArea offset="0 1.65 0.48" width="2.4" height="3.5" length="7.25"/>
        </vehicleConfiguration>		
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD616K.xml" selectedConfigs="8">
            <loadingArea offset="0 1.65 0.48" width="2.8" height="3.5" length="7.25"/>
        </vehicleConfiguration>			
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD83.xml" selectedConfigs="1,5,7">
            <loadingArea offset="0 1.65 0" width="2.35" height="3.3" length="6.2"/>
        </vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD83.xml" selectedConfigs="8">
            <loadingArea offset="0 1.65 0" width="2.6" height="3.3" length="6.2"/>
        </vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD616.xml" selectedConfigs="1,5,7">
            <loadingArea offset="0 1.65 0.48" width="2.4" height="3.5" length="7.25"/>
        </vehicleConfiguration>		
		<vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD616.xml" selectedConfigs="8">
            <loadingArea offset="0 1.65 0.48" width="2.8" height="3.5" length="7.25"/>
        </vehicleConfiguration>	
```
here is the link: https://www.farming-simulator.com/mod.php?mod_id=226713&title=fs2022

**Comment by DrewCZ** [comment]
unfortunately, today - with the same config - it loads only one row of bales. 
I don't know why, investigating yet.

**Comment by ddewar** [comment]
Hmm, interesting. Bales will allow you to load while moving I think, so it you are moving when it places the bales it can get funky. Bales are usually a minor test for me. They don't stack well right now, so until there is a true bale mode, I wouldn't worry too much about it. 

But I did try to pull the configs in. Sizes look pretty good. Any reason to configure just for the tippers? I can apply them to the others unless you ran into some problems.

**Comment by ddewar** [comment]
I did a little more testing, looks like the y-offset of the loading zones, 1.7 moved it out of the bed of the trailer and forced it to be more consistent.

Sometimes the bales will "pop" out of the bed when the loading zone is too low. Then when the next row goes to get placed on top, it sees the space as occupied until the bale has settled.

**Comment by DrewCZ** [comment]
thank you @ddewar for your response. 
I was trying the same and confirmed that it works well after rising up Y coord it works well! 
Let me add the rest of the configs and repair existing (today evening?)

**Comment by ddewar** [comment]
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v0.0.7-beta
