### ISSUE TITLE
Trailer requests

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#22]
Any chance these mods will be added? 

I tried to add it myself but caused a major headache and crashed my system 😬

https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=242221&title=fs2022

https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=242220&title=fs2022

https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=238153&title=fs2022

**Comment by ddewar** [comment]
I will do my best to get these into the next update! One of them was already on my list. I'll update this issue, so you know when they're added.

**Comment by judg393** [comment]
Thank you very much

**Comment by ddewar** [comment]
Addressed in 98cb2531cc26723afed1ac5d3f2392e8f4f39a65, c7b857f3333a59b2cbfe9cf2359349fa9ab11f71, and 943ead2c2869500a9d710aa08b4933d663c69beb

**Comment by ddewar** [comment]
Check out the newest release for this trailer: https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v0.0.8-beta

**Comment by judg393** [comment]
Thank you (I hope this doesn't reopen
