### ISSUE TITLE
Trailer support

### ISSUE THREAD

**Issue by Rlc89** [ddewar/FS22_UniversalAutoloadModhubAddon#23]
Was just wondering if you have plans to add the new van trailer. [van trailer](https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=248424&title=fs2022) thank you.

**Comment by ddewar** [comment]
Adding in commit 93bcbdf93461386a94b6c698df85cc8780d3f36c.

**Comment by ddewar** [comment]
Check out the newest release for this trailer: https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v0.0.8-beta
