### ISSUE TITLE
Congrats (82s Global Pallet Support)

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#24]
Congrats on a modhub release mate this is a great addition to UAL :) 

Just a quickie any idea on a time frame or if you intend to add support for 82's big bag mod ? 

https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=250753&title=fs2022

I tried loading it hoping it would recognise it but no luck. 

Equally if you have a tutorial on how I can add it myself :)

**Comment by ddewar** [comment]
Thanks very much! Glad to get this into more people's games.

I will look into it ASAP! I've been eyeing that too. I'm guessing it's not a standard pallet so I might have to get Loki involved. I'll get back to you soon.

**Comment by judg393** [comment]
Cheers my man :)

**Comment by ddewar** [comment]
Just an update on this. This pallet is not set as a true pallet, but rather a custom type. I will be working with Loki on adding this as a supported type, but just a warning it might be a bit while we wait for his next update.

**Comment by judg393** [comment]
I did wonder when it wasn't picked up automatically and it has all those magic bits. 

If there's anything I can do let me know otherwise I'll be patient :)

**Comment by ddewar** [comment]
Closed by https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.1

Please reopen if any issues.

**Note:** this will only work with newer versions of UAL. https://github.com/loki79uk/FS22_UniversalAutoload/releases
