### ISSUE TITLE
itrunner

### ISSUE THREAD

**Issue by discord5000** [ddewar/FS22_UniversalAutoloadModhubAddon#25]
Hi mate, well done on an awesome mod!
Any chance of adding support for the it-runner hooklift platforms?

**Comment by ddewar** [comment]
Hey there, if you can shoot me a link for which one you mean, I can for sure take a look at them.

**Comment by discord5000** [comment]
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=247553&title=fs2022
and
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=232175&title=fs2022

**Comment by ddewar** [comment]
![image](https://user-images.githubusercontent.com/15822357/185641868-0f31baea-df84-4515-8990-740a5a988bb3.png)
![image](https://user-images.githubusercontent.com/15822357/185642092-667bff44-d4cf-406a-bae8-7390eb8ae3db.png)

Making some progress on here. Here is a link to the commit if you want the working ITRunner part. Working on the Transport flatbed still.

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/commit/af97c9e4cea3b1bd1c3351a2c76035069fbd8a6d

**Comment by ddewar** [comment]
And you can find the transport config in this commit:
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/commit/8ab71649c96f666d449327ef8553d7bd1956613e

The whole thing should be part of my next 1-click download here on github in a few days. Just wrapping up a few other trailer requests.

**Comment by discord5000** [comment]
You rock! thank you so much!

**Comment by ddewar** [comment]
Closed by https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.1

Please reopen if any issues.


Keep in mind the flatbed might be a little weird. That mod has some weirdness. Loki and I will try to get back to it if we find a good solution.
