### ISSUE TITLE
Add a new trailer

### ISSUE THREAD

**Issue by M0lyk** [ddewar/FS22_UniversalAutoloadModhubAddon#27]
Hi, can you please add this trailer ?

https://www.farming-simulator.com/mod.php?mod_id=237992&title=fs2022

**Comment by ddewar** [comment]
I'll get it in the next release. :)

**Comment by ddewar** [comment]
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/commit/53930d273f039c1ff9be18174ec9b2e41ed0f456

Should be good in the next release. Github version hopefully in a few hours.

**Comment by ddewar** [comment]
Closed by https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.1

Please reopen if any issues.
