### ISSUE TITLE
More Truck support

### ISSUE THREAD

**Issue by SimonSchw** [ddewar/FS22_UniversalAutoloadModhubAddon#28]
Hi! 
Love the project, could you add support for more Trucks other than the MAN?

Here are some that I wish I could use with your mod :)

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=245649&title=fs2022
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=252000&title=fs2022
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=251870&title=fs2022
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=247596&title=fs2022
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=246086&title=fs2022
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=243003&title=fs2022

**Comment by ddewar** [comment]
Hey there, sounds like a great idea. I'll see if any of these have issues, and get them into the next release. I'll update here when I have them working.

**Comment by ddewar** [comment]
Probably going to skip 
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=247596&title=fs2022

For now. It's a little problematic for me currently. Feel free to open a new issue with that one. I will get around to it eventually.

**Comment by ddewar** [comment]
All others have been added in my latest commits. Github release soon. 

Note: The Tatra has some weird collisions so I had to start the zone back a bit. Might look odd, but works fine.

**Comment by ddewar** [comment]
Closed by https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.1

Please reopen if any issues.
