### ISSUE TITLE
Quick question about the "Bailey Bale and Pallet Trailer"

### ISSUE THREAD

**Issue by Gariot** [ddewar/FS22_UniversalAutoloadModhubAddon#30]
Hey!

First of all - thank you for your work on this one, its pretty cool and i appreciate it! :) 

The other day i got the Trailer [Bailey Bale And Pallet Trailer](https://farming-simulator.com/mod.php?mod_id=228030&title=fs2022) to load some Honey. I dont know if its intended but he only loads one row/layer of pallets and thats it. If its intended then i will shut up of course :D But it would be cool if i could at least load 2 rows.

Thanks and stay healthy! :)

**Comment by ddewar** [comment]
Hey! I will have to give this a try next time I'm on farming sim. I'm guessing it's the weight of the pallets making Universal Autoload believe it shouldn't stack higher than 1. The lighter the trailer the less UAL tries to stack on it vertically. 

Will confirm and get back with a for sure answer for you though. If it is the weight issue, I will check in with Loki and see if we can make it less restrictive.

**Comment by ddewar** [comment]
Check out Loki's newest release.

https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.2.0

Might make this better.

**Comment by ddewar** [comment]
Closing as I believe Loki has addressed this issue. Please reopen if needed.
