### ISSUE TITLE
How can I help to add support for the Univers Simu Modding trailers ?

### ISSUE THREAD

**Issue by Lactic68** [ddewar/FS22_UniversalAutoloadModhubAddon#4]
Hi,
I am in contact with @loki79uk and I would know if I can help to add support for all trailers of [Univers Simu Modding](https://www.farming-simulator.com/mods.php?lang=fr&country=fr&title=fs2022&filter=org&org_id=118016&page=0) ?

I was thinking about : 
- Rolland Pack
- Ponge Pack
- Perard Pack

Best regards,

**Comment by ddewar** [comment]
Hey there,

Would love some help with those packs. 2 options for getting them in the pack:

1. Create a fork of the repo. Add your changes. (Preferably a commit for each pack) Open up a PR. I will test them out and merge them in.
2. Just send me your config file for the packs and I will split them out and add them in.

Let me know if you have any questions. Happy to get more mods supported!

**Comment by Lactic68** [comment]
Great, I just have submitted a PR #5 with all necessary settings for appropriate mods. Tested on single player.

**Comment by ddewar** [comment]
PR #7 Closes this issue.
