### ISSUE TITLE
TLX Phoenix Logger Bed

### ISSUE THREAD

**Issue by FrmrJon** [ddewar/FS22_UniversalAutoloadModhubAddon#40]
Hi ddewar, I went ahead and added UAL to the TLX Phoenix log bed. Let me know if you'd like the code to add it to the mod.

**Comment by ddewar** [comment]
Please send it on over! I haven't been able to go back around to the TLX stuff again since Loki gave us more fun tools to configure. I'll get it in to a GitHub release for everyone to use.

**Comment by FrmrJon** [comment]
Here is the code I added:
`        <vehicleConfiguration configFileName="FS22_TLX_Phoenix/attachments/logger_x2.xml" modHubId="242995">
            <loadingArea offset="0 1.30200005 -0.88664109" width="2.35" height="2.00" length="6.2"/>
            <options isLogTrailer="true" />
        </vehicleConfiguration>
`
