### ISSUE TITLE
Trailers request - increase loading area

### ISSUE THREAD

**Issue by bojanh66** [ddewar/FS22_UniversalAutoloadModhubAddon#41]
Here is the link to the trailers:
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=225090&title=fs2022
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=228030

Bailey trailer can probably accept 2 more pallets, while Rolland trailer can accept 4 more pallets.
I have experimented with Rolland trailer in the game, left row is manually stacked pallets row and right row is universal autoload, as you can see, it can take more pallets, i would be grateful if you could increase their loading area, these are my favorite trailers.
![FarmingSimulator2022Game 2022-11-23 20-32-27](https://user-images.githubusercontent.com/32069662/203632810-14717eb0-1355-46e5-aa66-fb00eb3d06f0.jpg)

**Comment by ddewar** [comment]
I have added an update for these trailers. The Rolland trailers now go end to end.

![image](https://user-images.githubusercontent.com/15822357/204033388-02c6a6b8-280d-4cd1-bb05-bde81a102932.png)
