### ISSUE TITLE
Adurante pack

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#42]
https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=232329&title=fs2022

Hey me again 

I've just tried to use the fs22 adurante pack and noticed it didn't show up with UAL in the store. I haven't checked if it works in game yet but I'd presume not if the stores not showing it. 

No idea if the reason is because the Modhub id in the supported vehicle xml points to the 19 page? Doubt it but wondered if you might want to know this anyway 

I will test the trailer asap and report back

**Comment by ddewar** [comment]
Hmmm, if I remember correctly with this mod, I basically had to just add it to the one version of the trailer. The autoload that came with the mod was conflicting on other trailers. Next time I am in the mod I will take a look and see if I am seeing something funny with it.

**Comment by judg393** [comment]
Ah maybe I just missed it will have another look.

**Comment by ddewar** [comment]
Good catch, this is bugged. Working on it.

**Comment by ddewar** [comment]
Just an FYI, this was an issue due to some name changes at some point. It should work now, but only on the first trailer in the pack, and when it is a non-tipper mode. Let me know if you have issues still.

**Comment by ddewar** [comment]
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.6

Latest version has these changes

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.6

**Comment by judg393** [comment]
I was just coming to say it defo doesnt seem to work.  I'll check I've got latest upload and try again :)

**Comment by judg393** [comment]
also the mod desc says i'm on v 1.1.0.0 (I'm pulling directly for Git hub so i presume its just a typo or something? as theres no changes to my folder according to the github desktop app) its probably not important

**Comment by judg393** [comment]
ok can confirm UAL added to the first version of the trailer in the pack at least on a syore level (no reason tothink it wont work in game) 

New question though all the other forestry trailers have UAL logo and then a length visible on the store page which is incredibly handy  the Adurante forest version just says UAL?

I was really hoping i could have 1 trailer that could be a flat bed with UAL and via configuration a UAL wood carrier  the light trailers great but i wanted something a bit longer. If the adurante is too complex do you have any suggestions on what i could use (Prefer none semi)

**Comment by ddewar** [comment]
It still should load logs; it just isn't set to be exclusively a log trailer. We treat them slightly differently in UAL. Let me know how it works, you can always add the isLogTrailer option to it in your UniversalAutoload.xml and create your own version. :) Let me know if you have any issues or questions.

**Comment by judg393** [comment]
Oh is that what makes it show up a length in the store? Would I just add "islogtrailer=yes" to the vehicle xml ?

**Comment by ddewar** [comment]
@loki79uk can confirm for you, but I am pretty sure yes.

**Comment by loki79uk** [comment]
`isLogTrailer="true"` (not yes), but otherwise you are correct.  The max length only shows up for dedicated log trailers, but be aware that then they won't load pallets and will load logs by dropping them from above into the trailer.

**Comment by judg393** [comment]
Thank you both!
