### ISSUE TITLE
script for new trailers

### ISSUE THREAD

**Issue by sofr-oleg** [ddewar/FS22_UniversalAutoloadModhubAddon#43]
add script support to the package Fliegl Timber Runner Pack                                                                                                         https://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=258564&title=fs2022

**Comment by ddewar** [comment]
Included in: https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.6

**Comment by sofr-oleg** [comment]
thank you very much.good luck
