### ISSUE TITLE
Shortwood Trailer and Truck

### ISSUE THREAD

**Issue by LSMT-elMatador** [ddewar/FS22_UniversalAutoloadModhubAddon#45]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=242219&title=fs2022

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=230299&title=fs2022

Hello, 
first of all a big thank you for this mod!

I tried to add these two mods to yours. Unfortunately logs are not stacked and thus the trucks/trailers are not utilised. I also have a difficult driving behaviour with vehicles loaded with logs. If you remove the tension belts, it gets a little better. 
Would it be possible to include these two vehicles in your mod?

**Comment by ddewar** [comment]
I'll take a look and see if I can get these in soon. Not sure it will help with stability issue, but let's see how it goes.
