### ISSUE TITLE
Bailey trailer - increase loading space

### ISSUE THREAD

**Issue by bojanh66** [ddewar/FS22_UniversalAutoloadModhubAddon#46]
Link to the mod:
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=228030

Could you increase loading space, there is enough space for 1 more row of pallets.

![FarmingSimulator2022Game 2022-11-28 17-46-50](https://user-images.githubusercontent.com/32069662/204334789-8f73735f-2c64-48a7-94a4-9cd718d02363.jpg)
![FarmingSimulator2022Game 2022-11-28 17-51-11](https://user-images.githubusercontent.com/32069662/204335488-0236c7fa-29ff-4c88-9f90-53848e2934bb.jpg)

**Comment by Dustbunney54** [comment]
Dec. 4, 2022  Mr. ddewar, this is also happening on logging trailers and other trailer types trying to load pallets,  being used on the Platinum Expansion map, Silver Run.  Is there a setting or something that can be done from my side prior to using these types of trailers? Thank you for your mod sir and thank you for your time.,

**Comment by ddewar** [comment]
@bojanh66 still working on this.

@Dustbunney54 do you have an example of what you're talking about? Not sure I've seen this issue.

**Comment by Dustbunney54** [comment]
Dec. 4, 2022  Mr. ddewar, the example is the same as the one in the screenshots posted previously by bohan66.  I was commenting to let you know that the same identical message is coming up while using logging trailers and other types of pallet loading trailers on the Platinum Expansion, Silver Run map. The message is "Loading area is full. Unable to load any  more items of this size".  Thank you sir, for your reply.

**Comment by bojanh66** [comment]
Hey, i made my own config after a few tests and i got what i wanted.
I can have 2nd row of pallets too, you can check it if u want and include it in your next update if u think its good.

<vehicleConfiguration configFileName="FS22_Bailey_Bale_Pallet_Trailer/BPTrailer.xml" modHubId="228030">
            <loadingArea offset="0 1.08 -1" width="2.55" height="2.50" length="7" baleHeight="2.50"/>
            <options isBaleTrailer="true" enableSideLoading="true"/>
        </vehicleConfiguration>

**Comment by ddewar** [comment]
> Hey, i made my own config after a few tests and i got what i wanted. I can have 2nd row of pallets too, you can check it if u want and include it in your next update if u think its good. Hmm, i dont know why, but config text doesnt want to show all, only part of it ? Anyway, here is the screenshot. "FS22_Bailey_Bale_Pallet_Trailer/BPTrailer.xml" modHubId="228030"> ![Untitled](https://user-images.githubusercontent.com/32069662/205521509-139d9178-b20d-4d45-8df9-bce77187a06a.jpg)

Thank you, I will add this to the next update. Your config looks good, I brought the height down slightly from what you're using, so you may want to keep your config so after the update it doesn't go back to smaller :)

**Comment by bojanh66** [comment]
@loki79uk 
Hello, i want to report an issue with Bailey trailer after today's update.
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=228030&title=fs2022

This is how it looks with 1.3.0.0 modhub update:
![fsScreen_2023_05_05_14_31_42](https://user-images.githubusercontent.com/32069662/236458665-b3e1d414-7110-4aa2-8a37-eadc97526118.png)

and this is how it looks with my custom xml configuration:
![fsScreen_2023_05_05_14_37_48](https://user-images.githubusercontent.com/32069662/236459497-15ee376e-a918-4ed5-b736-afb7331197a2.png)

My config is exactly the same as in previous post, so i have compared yours and mine and you have changed height slightly and offset which probably caused this small issue.
Just want to let you know about this.

**Comment by KingArthurLV** [comment]
Created fix for this. Adjusted offset and loading area. Also added second configuration for trailers without back guards to acomodate extra row of pallets.
