### ISSUE TITLE
FS22_50ft_Gooseneck_Trailer log loading

### ISSUE THREAD

**Issue by wriley** [ddewar/FS22_UniversalAutoloadModhubAddon#49]
This trailer will only load 1 row of logs then says it's full. It tried playing around with the height and length in the user modSettings file with no luck. I'm using the 40ft config option
![20221202111128_1](https://user-images.githubusercontent.com/532318/205354778-9e252af3-f527-4979-836e-83f144c2553a.jpg)
![20221202112549_1](https://user-images.githubusercontent.com/532318/205354796-bbff34d8-932c-4a33-94bb-b67562f7a3f2.jpg)

**Comment by wriley** [comment]
I dug further into the code, please disregard

**Comment by ddewar** [comment]
Just curious what caused it?

**Comment by wriley** [comment]
This is a flatbed trailer so didn't have isLogTrailer="true" by default. One of the store configuration options is to add foldable log stakes. I added isLogTrailer="true" in the user xml and it now works as expected. Thanks for a great addon!

**Comment by ddewar** [comment]
Ah yes, with so many config options on that trailer, I had to skip out on adding that by default. Glad you got it working!
