### ISSUE TITLE
Autoload Query

### ISSUE THREAD

**Issue by B2992** [ddewar/FS22_UniversalAutoloadModhubAddon#52]
Hello,

Would like to start off by thanking you for this fantastic mod and the work you've put into it. 
I had a question regarding the additional trailers that come with mods like the TLX 2020 and the John Deere Gator. Would it be possible to add support for the additional trailer modules that come with them (ex. TLX 2020 Log-IT or the TLX 2020 flat bed) or will only selected configurations support auto load?

Also would it be possible to add support for the [Lizard Minor 6x4](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=260194&title=fs2022) that just recently released.

**Comment by ddewar** [comment]
I believe I had added most of the things you requested. Let me know if I missed any or if you have any other requests. Changes should be in [newest release](https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.1.0.1).
