### ISSUE TITLE
Config query

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#55]
_Hi buddy 

Quick query I think there was some changes made to the GitHub version day before yesterday ? Maybe not but I'm sure something updated. I'm running the TLX Phoenix in rigid mode with an X2 logger on the back and the tlx pup trailer with another x2 logger and until a couple of days ago it was great. 

Now it appears the x2 on the truck has a much smaller cap than the x2 on the trailer was anything changed ? Literally can't get the truck x2 to take more any way I try but last week it definately did. 
🤷‍♂️ I'm totally lost and confused 

 ![image](https://user-images.githubusercontent.com/55981682/207687342-4a8fbbd6-6669-4846-bb44-cbceccad4d45.jpeg)![image](https://user-images.githubusercontent.com/55981682/207687343-f9fe899f-749f-4223-9906-d63efb24251b.jpeg)_

**Comment by ddewar** [comment]
That's very interesting. Is the attachment on the pup and the truck the same attachment? (sorry, I haven't used the TLX much so that might be a silly question)

If you push ctrl+shift+F12 you should get a more detailed debug showing you the loading zones and their heights. Might give you an idea of is causing the issue. I will do my best to try this next time I get a chance and see if it does the same for me.

**Comment by judg393** [comment]
Hi buddy 

Yup exactly the same attachment on truck and trailer. 
Not sure If the below will help. I'll try resetting the truck attachment next time I play see if that helps it 


![image](https://user-images.githubusercontent.com/55981682/207814062-5b6326fe-b00a-484e-9fcd-c0ec10dcf5e9.jpeg)

**Comment by judg393** [comment]
I tried resetting and it didn't help also tried switching the backs around so pup was on trailer and vice a versa no help truck back still only loads 2 layers of logs and trailer 3-4-5. Baffling but it's not a huge issue

**Comment by judg393** [comment]
seems to have resolved itself  @ddewar trailer now loads beyond two levels

**Comment by ddewar** [comment]
> seems to have resolved itself  @ddewar trailer now loads beyond two levels 

This is so weird. I'm going to be investigating more. (The holidays got in the way) But thank you for keeping me updated.
