### ISSUE TITLE
Dropdeck Auto trailer 53ft CROSS PLAY

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#56]
Hi @ddewar dan 

 you might need to check your coding of the mod above. It's got the wrong config numbers (or it's had an update or a reorder that's messed up the config count knowing this mod it's likely. It's the first trailer in the pack that needs changing I believe and this file should fix it for you :)

https://www.dropbox.com/s/fiw2xlxsdpl2rjp/SupportedVehicles.xml?dl=0

sorry ive no idea whether i should fork or spoon this or even knife it :)

**Comment by ddewar** [comment]
Thank you for the code, I'll give it a try. I think that mod had some updates. It's messy one. 😅

**Comment by judg393** [comment]
That's for sure! Your very welcome and merry Christmas 😂

**Comment by judg393** [comment]
Dude I have a GitHub question I've made some further alterations to the loading area of the TLX logger trailer (the 5th wheel x52 logger) (it was bugging me that it was only 0.5m short of 3 full logs so I have adjusted it.) Now obviously this is my own alteration that may not suit anyone is there a way I can keep my changes and keep up to date with your changes ? I mean your welcome to publish my changes but they may not be for everyone. Hope that makes sense not sure if it does

**Comment by ddewar** [comment]
> Dude I have a GitHub question I've made some further alterations to the loading area of the TLX logger trailer (the 5th wheel x52 logger) (it was bugging me that it was only 0.5m short of 3 full logs so I have adjusted it.) Now obviously this is my own alteration that may not suit anyone is there a way I can keep my changes and keep up to date with your changes ? I mean your welcome to publish my changes but they may not be for everyone. Hope that makes sense not sure if it does 

If you put your changes in your UniversalAutiload.Xml in the modSettings folder, that piece of equipment will always use your config instead of the GitHub version. The only thing you wouldn't get with this approach is any changes I make to that specific piece of equipment.

**Comment by judg393** [comment]
thank you mate I'll check it out :)

**Comment by ddewar** [comment]
> 

I believe this mod has included it's own UAL implementation now. I am going to remove this from my mod and close this issue. Let me know if you find any problems.

**Comment by judg393** [comment]
Thanks mate.
