### ISSUE TITLE
IT Runner Short Wood Platform

### ISSUE THREAD

**Issue by LordKnechtus** [ddewar/FS22_UniversalAutoloadModhubAddon#57]
Hi, 

i have a Problem. When i try to load wood with the short IT-Runner Wood Platform, i only can load like 3 wood, then it will say, that there is no more room, but the trailer is like 3 meters High and empty.

**Comment by ddewar** [comment]
Hmm let me take a look. We've been seeing issues like this with some wood trailers. My suggestion would be try to move the zone a little bit if you have made any custom zones. It might be colliding with something.

**Comment by LordKnechtus** [comment]
![fsScreen_2023_01_02_17_46_49](https://user-images.githubusercontent.com/118667543/210259425-21ae4632-019f-4400-a735-bae73fa2f033.png)

Here you can see my problem. Sometimes i can load full, sometimes just 3 trees...

**Comment by ddewar** [comment]
Just an FYI, I have figured out this issue and will have a fix in the next release. If you want a fix in the meantime, you can copy the IT Runner configs to your local UniversalAutoload.xml in the modsettings folder and uncomment the option.

```<options isLogTrailer="true"/>```

I had configured these trailers to accept wood but also pallets and bales. This made the UniversalAutoload mod load in a non-logging fashion. This resulted in it viewing the trailer as full when it was not. Hopefully this helps, sorry for the wait.
