### ISSUE TITLE
Komatsu Forwarder Pack (HR Forst und Fahrzeugbau)

### ISSUE THREAD

**Issue by MrSaffron** [ddewar/FS22_UniversalAutoloadModhubAddon#60]
Now i don't know what i'm doing wrong but in version 1.1.0.1 it says this is included. https://www.farming-simulator.com/mod.php?mod_id=247034&title=fs2022  have tried in all different lengths 

//MrSaffron

**Comment by ddewar** [comment]
Hmmm, I have been able to confirm, this is included in the mod and I am seeing it in my game. I know this issue is a few weeks old, did you ever get it figured out?

**Comment by MrSaffron** [comment]
![image](https://user-images.githubusercontent.com/119298475/215040456-2ab62193-6208-4cfe-b49b-2323bb533f08.png)
so I get up when I run with the latest one.

**Comment by KingArthurLV** [comment]
Created fix for this ticket. Issue was with length value, too short loading area for 5m logs. Also removed heightAxis="AXIS_CRANE_TOOL3" trigger since it causes override height set value and creates very high log stacks.
