### ISSUE TITLE
Lizard TP 10M

### ISSUE THREAD

**Issue by SSlz** [ddewar/FS22_UniversalAutoloadModhubAddon#63]
please can you supply this low loader "Lizard TP 10M" with the mod? 

this is my favorite transport trailer. I would be very happy

Thank you very much in advance. 

Sebastian

**Comment by ddewar** [comment]
Hey, I will look into this for the next update. Have a link to the mod for me?

**Comment by SSlz** [comment]
https://farming-simulator.com/mod.php?lang=de&country=de&mod_id=249931&title=fs2022

**Comment by ddewar** [comment]
Added in https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/commit/4e8c95fd1ac8d31042b546e57c9f329e088ded91

Will be included in the next release, keep an eye out for it. Should be on Github in a few days.

**Comment by SSlz** [comment]
do the updates also appear in the FS22modhub (in the game)?I am very happy about the fast support.

**Comment by ddewar** [comment]
They will get to modhub eventually. I usually wait until I get a sizable amount of changes here on GitHub before I push Loki to update it.
