### ISSUE TITLE
Fliegl Low Loader Trailer Pack

### ISSUE THREAD

**Issue by RobTomcat** [ddewar/FS22_UniversalAutoloadModhubAddon#64]
Any chance you could add the Fliegl Low Loader Pack v1.2 by HR Forst und Fahrzeugbau to your list of supported low loaders please?  Specifically the Fliegl STS but the others in the pack would be useful too.

Thanks,  Rob

**Comment by ddewar** [comment]
Hey @RobTomcat are these modhub mods? If so do you have a link? We're too the point where the number of mods on modhub is making it hard for me to find things, 😬 

If it's not on modhub, send me a link anyway and I'll see if I can set up a config for ya.

**Comment by RobTomcat** [comment]
Hi  Dan

Appreciate your response.  Link is https://www.fs22modhub.com/fliegl-lowloader-pack-v1-2/  It even has pictures of bales on the trailers!

**Comment by ddewar** [comment]
Does this look like the same mod to you?

https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=241879&title=fs2022

I'll download them myself after work and compare if you're not sure, but either way I'll work on a config and let you know.

**Comment by RobTomcat** [comment]
Yes, that is the mod definitely.  Thanks.

**Comment by ddewar** [comment]
Please verify for me, but I think this was included in release v1.2.1.0

**Comment by RobTomcat** [comment]
Hi Dan

Yes, thanks, I can confirm the Fliegl STS - the only trailer I have used from the Fliegl Low Loader Pack - loads bales perfectly with the update you provided v1.2.0.0 in March.  I had assumed, without checking, this thread had been closed when you released that mod with the update.  

Works perfectly, many thanks.

Rob
