### ISSUE TITLE
Added support list

### ISSUE THREAD

**Issue by KingArthurLV** [ddewar/FS22_UniversalAutoloadModhubAddon#87]
Hi @ddewar! Here I will post created supports for trailers, which I will make PR as soon You will accept #81.

- Support for [FS22_HomemadeFlatbedTrailer](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=267779&title=fs2022)
- Support for [FS22_OT2000](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=268840&title=fs2022)

**Comment by ddewar** [comment]
Should have the other PR done soon. Had to run out of town for a few days for a wedding.
