### ISSUE TITLE
Request for vehicle support 

### ISSUE THREAD

**Issue by SSlz** [ddewar/FS22_UniversalAutoloadModhubAddon#88]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=269308&title=fs2022

In this package there is a trailer. Could it get an autoload function?

**Comment by SSlz** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=233021&title=fs2022

Another trailer.

**Comment by SSlz** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=233021&title=fs2022

Another trailer.

**Comment by SSlz** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=249686&title=fs2022

Another one.

**Comment by SSlz** [comment]
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=249686&title=fs2022

Another one.

**Comment by ddewar** [comment]
@SSlz I added your 3 mod requests in my last commit and they will be part of the next release. 

@Adubmodding I moved your request to it's own issue to track it easier.
