### ISSUE TITLE
No autoload available on Ponge Trailers when configured without sideboards

### ISSUE THREAD

**Issue by Lactic68** [ddewar/FS22_UniversalAutoloadModhubAddon#9]
Hi @ddewar ,
We have started to show your work (and Loki's) and we have noticed that when the Ponge trailers which are configured without sideboards don't show any UA abilities. This is something to do with `<options noLoadingIfUnfolded="true"/>`. Maybe we can delete this properties ? Or maybe we have to specify in which configurations UA might be available ?
![2022-04-29_13-47-27](https://user-images.githubusercontent.com/70093234/165944517-c5a053ff-52bf-46b2-b8b0-236938d14e73.png)

**Comment by ddewar** [comment]
That's very interesting. I don't think that property should do anything like that, but I would guess it thinks it's always folded? The trailer is probably set up in a bit of a funky way. I wonder if Loki has any ideas. Or if he's ready to enable different options per selectedConfig. 😉 I'll reach out to him and see if he knows what's up. I'm out of town for a few days, but the easy solution is probably that we just remove that option from the Ponge pack for now.

**Comment by ddewar** [comment]
Accepted PR. Going to close this for now unless the main mod gets some enhancements.
